// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-QVu5aB1if7blfsgj-7n3a232lEp0nA8',
    appId: '1:951189836596:web:e52a4ae54c424170d34b61',
    messagingSenderId: '951189836596',
    projectId: 'flutter-fire-umer-v2-30abf',
    authDomain: 'flutter-fire-umer-v2-30abf.firebaseapp.com',
    storageBucket: 'flutter-fire-umer-v2-30abf.firebasestorage.app',
    measurementId: 'G-7D3VPPTL7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhPKGf5D98_E_fCNrkkqV2Hkx3NcghCAA',
    appId: '1:951189836596:android:ff4b219054986981d34b61',
    messagingSenderId: '951189836596',
    projectId: 'flutter-fire-umer-v2-30abf',
    storageBucket: 'flutter-fire-umer-v2-30abf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbiZ6dOEjkvzDrQ35RPDIa13wK4xEyEK4',
    appId: '1:951189836596:ios:3b6237b939d2fad0d34b61',
    messagingSenderId: '951189836596',
    projectId: 'flutter-fire-umer-v2-30abf',
    storageBucket: 'flutter-fire-umer-v2-30abf.firebasestorage.app',
    iosBundleId: 'com.example.project1practice',
  );
}
